repos:
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        additional_dependencies: ['toml']
        exclude: >
            (?x)^(
                loki/.*|
                logcli/.*|
            )$

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        exclude: >
          (?x)^(
              loki/.*|
              logcli/.*|
          )$

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [pyproject-flake8]
