# SPDX-FileCopyrightText: 2023 SUSE LLC
#
# SPDX-License-Identifier: Apache-2.0

global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: uyuni-health-exporter
    static_configs:
      - targets: ['host.containers.internal:9000']
